# Generated by Django 4.0.4 on 2022-06-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshot', '0002_alter_screenshot_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='images/temp'),
        ),
    ]
